### ISSUE TITLE
len attribute to get the number of children not functioning (not implemented?)

### ISSUE THREAD

**Issue by scottfleming** [som-shahlab/femr#80] opened 2023-02-09 21:38 UTC
## Steps to reproduce the bug
```python
source = "/local-scratch/nigam/projects/ethanid/som-rit-phi-starr-prod.starr_omop_cdm5_deid_2023_01_02_extract_v7"
data = piton.datasets.PatientDatabase(source)
code_dictionary = data.get_code_dictionary()
print(len(ontology.get_children(1000)))  # prints "0"
for i in range(1_000):
    # Will dutifully print 1000 codes
    print(i, ontology.get_children(1000)[i])
```

## Expected results
I would expect
(1) calling `len` on `ontology.get_children(7)` would get an iterator for a finite-length (potentially empty) list of children of code 7 in the ontology.
(2) Indexing into this iterator beyond the length of that list would throw an out-of-bounds exception

## Actual results
(1) Length is reported to be zero
(2) There is no out-of-bounds error when indexing into the returned list

## Environment info

- `datasets` version: Extract v7 of piton
- Platform: Linux
- Python version: `Python 3.10.4`

**Comment by Lalaland** [comment] 2023-02-09 23:21
Just as an FYI for what is going on here. This code has no children. Len is correctly returning 0.

The issue is that the out of bounds checking for this code had a bug, which I fixed in the linked PR.

**Closed** 2023-02-27 18:07 UTC
